package com.titan.irgs.fileupload.enums;

public enum FileUploadType 
{
	  BRAND,MODEL,CLUSTER,PROPOSED_MOVEMENT,MOVEMENT_EXISTING,PRICE_BAND,TYPES,VENDOR,CURRENCY, Asset, Equipment, EpStore, Vendor, COUNTRY, STATE, REGION, CITY, EQUIPMENTINVENTORYDETAIL,OPTO,
	  AREAMANAGER,OPTOTRANSFER,PMACTIVE, Engineer,INVENTORY,INVENTORYAmc,InventoryAmcExtn,Store,ASSETSPECIFICATION,User

}
